services:
  # Redis
  - type: redis
    name: django-air-redis
    plan: free
    ipAllowList: []

  # Django Web
  - type: web
    name: django-air-web
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-air-db
          property: connectionString
      - key: CELERY_BROKER_URL
        value: redis://django-air-redis:6379/0
      - key: CELERY_RESULT_BACKEND
        value: redis://django-air-redis:6379/0
      - key: DJANGO_SECRET_KEY
        value: PLACEHOLDER_DJANGO_SECRET_KEY
      - key: STRIPE_API_KEY
        value: PLACEHOLDER_STRIPE_KEY
      - key: GOOGLE_CLIENT_ID
        value: PLACEHOLDER_GOOGLE_CLIENT_ID
      - key: GOOGLE_CLIENT_SECRET
        value: PLACEHOLDER_GOOGLE_CLIENT_SECRET

  # Celery Worker
  - type: worker
    name: django-air-worker
    runtime: docker
    dockerCommand: celery -A air worker --loglevel=info --pool=solo
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-air-db
          property: connectionString
      - key: CELERY_BROKER_URL
        value: redis://django-air-redis:6379/0
      - key: CELERY_RESULT_BACKEND
        value: redis://django-air-redis:6379/0
      - key: DJANGO_SECRET_KEY
        value: PLACEHOLDER_DJANGO_SECRET_KEY
      - key: STRIPE_API_KEY
        value: PLACEHOLDER_STRIPE_KEY
      - key: GOOGLE_CLIENT_ID
        value: PLACEHOLDER_GOOGLE_CLIENT_ID
      - key: GOOGLE_CLIENT_SECRET
        value: PLACEHOLDER_GOOGLE_CLIENT_SECRET

  # Celery Beat
  - type: worker
    name: django-air-beat
    runtime: docker
    dockerCommand: celery -A air beat --loglevel=info
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-air-db
          property: connectionString
      - key: CELERY_BROKER_URL
        value: redis://django-air-redis:6379/0
      - key: CELERY_RESULT_BACKEND
        value: redis://django-air-redis:6379/0
      - key: DJANGO_SECRET_KEY
        value: PLACEHOLDER_DJANGO_SECRET_KEY
      - key: STRIPE_API_KEY
        value: PLACEHOLDER_STRIPE_KEY
      - key: CLIENT_ID
        value: PLACEHOLDER_GOOGLE_CLIENT_ID
      - key: CLIENT_SECRET
        value: PLACEHOLDER_GOOGLE_CLIENT_SECRET

databases:
  - name: django-air-db
    plan: free