# Generated by Django 5.2 on 2025-04-10 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airplane",
            name="name",
            field=models.CharField(help_text="Name of Airplane", max_length=100),
        ),
        migrations.AlterField(
            model_name="flight",
            name="airplane",
            field=models.ForeignKey(
                help_text="Choose airplane from list",
                on_delete=django.db.models.deletion.CASCADE,
                to="air.airplane",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Base price for flight without additional services",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="flight_number",
            field=models.CharField(
                help_text="Unique flight number for each flight",
                max_length=10,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_number", models.CharField(max_length=5)),
                ("options", models.JSONField(default=dict)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("is_checked_in", models.BooleanField(default=False)),
                ("is_boarded", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="air.flight"
                    ),
                ),
                (
                    "passenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "luggage_weight",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="air.ticket"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BoardingPass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gate_number", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="air.ticket"
                    ),
                ),
            ],
        ),
    ]
