# Generated by Django 5.2 on 2025-04-29 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("air", "0002_alter_airplane_name_alter_flight_airplane_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flight",
            name="airplane",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="origin",
        ),
    ]
