# Generated by Django 5.2 on 2025-05-12 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air", "0003_remove_flight_airplane_remove_flight_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardingpass",
            name="boarding_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flight",
            name="airplane",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flights",
                to="air.airplane",
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="destination_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="flight",
            name="origin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="flight",
            name="origin_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="ticket",
            name="booking_reference",
            field=models.CharField(
                default="QTZCU9G2B6", editable=False, max_length=10, unique=True
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="seat_class",
            field=models.CharField(
                choices=[
                    ("economy", "Economy"),
                    ("business", "Business"),
                    ("first", "First"),
                ],
                default="economy",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="airplane",
            name="name",
            field=models.CharField(help_text="Name of the airplane", max_length=100),
        ),
        migrations.AlterField(
            model_name="boardingpass",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boarding_pass",
                to="air.ticket",
            ),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkins",
                to="air.ticket",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Base price (without services)",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="flight_number",
            field=models.CharField(
                help_text="Unique flight number", max_length=10, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="air.flight",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="options",
            field=models.JSONField(
                default=dict, help_text="Extra services like meals, luggage, etc."
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="passenger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
