# Generated by Django 5.2 on 2025-05-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air", "0004_boardingpass_boarding_time_flight_airplane_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="airlineuser",
            name="balance",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="booking_reference",
            field=models.CharField(
                default="IZPDSBM3VF", editable=False, max_length=10, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="options",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Extra services like meals, luggage, etc.",
                null=True,
            ),
        ),
    ]
