# Generated by Django 5.2 on 2025-05-14 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("air", "0005_remove_airlineuser_balance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="booking_reference",
        ),
    ]
