# Generated by Django 5.2 on 2025-05-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air", "0006_remove_ticket_booking_reference"),
    ]

    operations = [
        migrations.CreateModel(
            name="DietaryOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the meal", max_length=100),
                ),
                ("description", models.TextField(help_text="Description of the meal")),
                ("price", models.FloatField(help_text="Price of the meal")),
                ("image_url", models.URLField(help_text="Image url of the meal")),
                (
                    "dietary_options",
                    models.ManyToManyField(
                        related_name="meals", to="air.dietaryoption"
                    ),
                ),
            ],
        ),
    ]
