# Generated by Django 5.2 on 2025-05-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air", "0007_dietaryoption_meal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Baggage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(help_text="Description of the baggage"),
                ),
                ("price", models.FloatField(help_text="Price of the baggage")),
                ("weight", models.FloatField(help_text="Weight of the baggage")),
            ],
        ),
        migrations.CreateModel(
            name="Comfort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.FloatField()),
            ],
        ),
    ]
