# Generated by Django 5.2 on 2025-05-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air", "0008_baggage_comfort"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="stripe_price_id",
            field=models.CharField(
                default=1, help_text="Stripe price id for payment", max_length=100
            ),
            preserve_default=False,
        ),
    ]
