# Generated by Django 5.2 on 2025-05-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air", "0009_meal_stripe_price_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="baggage",
            name="stripe_price_id",
            field=models.CharField(
                default=1, help_text="Stripe price id for payment", max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comfort",
            name="stripe_price_id",
            field=models.CharField(
                default=1, help_text="Stripe price id for payment", max_length=100
            ),
            preserve_default=False,
        ),
    ]
