# Generated by Django 5.2 on 2025-05-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air", "0010_baggage_stripe_price_id_comfort_stripe_price_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="options",
        ),
        migrations.AddField(
            model_name="ticket",
            name="baggage",
            field=models.ManyToManyField(
                blank=True, related_name="tickets", to="air.baggage"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="comforts",
            field=models.ManyToManyField(
                blank=True, related_name="tickets", to="air.comfort"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="meals",
            field=models.ManyToManyField(
                blank=True, related_name="tickets", to="air.meal"
            ),
        ),
    ]
