# Generated by Django 5.2 on 2025-05-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air", "0011_remove_ticket_options_ticket_baggage_ticket_comforts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="booking_reference",
            field=models.CharField(
                default="5OA4V1UN99", editable=False, max_length=10, unique=True
            ),
        ),
    ]
