# Generated by Django 5.2 on 2025-05-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air", "0012_ticket_booking_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="gate",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="booking_reference",
            field=models.CharField(
                default="OJMI1VEQ3N", editable=False, max_length=10, unique=True
            ),
        ),
    ]
