# Generated by Django 5.2 on 2025-05-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air", "0013_ticket_gate_alter_ticket_booking_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.TextField(
                choices=[
                    ("upcoming", "Upcoming"),
                    ("canceled", "Canceled"),
                    ("boarding", "Boarding"),
                    ("checked_in", "Checked In"),
                    ("used", "Used"),
                ],
                default="upcoming",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="booking_reference",
            field=models.CharField(
                default="6KRNGGMDF6", editable=False, max_length=10, unique=True
            ),
        ),
    ]
