# Generated by Django 5.2 on 2025-05-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air", "0014_ticket_status_alter_ticket_booking_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="booking_reference",
            field=models.CharField(
                default="S4IAEBKC50", editable=False, max_length=10, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="gate",
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.TextField(
                choices=[
                    ("upcoming", "Upcoming"),
                    ("canceled", "Canceled"),
                    ("boarding", "Boarding"),
                    ("checked_in", "Checked In"),
                    ("used", "Used"),
                ],
                default="upcoming",
                max_length=20,
            ),
        ),
    ]
