# Generated by Django 5.2 on 2025-05-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air", "0015_alter_ticket_booking_reference_alter_ticket_gate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="status",
            field=models.CharField(
                choices=[
                    ("upcoming", "Upcoming"),
                    ("canceled", "Canceled"),
                    ("used", "Used"),
                ],
                default="upcoming",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="booking_reference",
            field=models.CharField(
                default="DF86TMCXVC", editable=False, max_length=10, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="gate",
            field=models.IntegerField(default=3),
        ),
    ]
