# Generated by Django 5.2 on 2025-05-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air", "0016_flight_status_alter_ticket_booking_reference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="status",
            field=models.CharField(
                choices=[
                    ("upcoming", "Upcoming"),
                    ("canceled", "Canceled"),
                    ("in_air", "In Air"),
                    ("arrived", "Arrived"),
                ],
                default="upcoming",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="booking_reference",
            field=models.CharField(
                default="XZA6CK1WF1", editable=False, max_length=10, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="gate",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.TextField(
                choices=[
                    ("upcoming", "Upcoming"),
                    ("canceled", "Canceled"),
                    ("boarded", "Boarded"),
                    ("checked_in", "Checked In"),
                    ("late", "Late"),
                    ("used", "Used"),
                ],
                default="upcoming",
                max_length=20,
            ),
        ),
    ]
