# Generated by Django 5.2 on 2025-05-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air", "0017_alter_flight_status_alter_ticket_booking_reference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="booking_reference",
            field=models.CharField(
                default="JRCUON78QD", editable=False, max_length=10, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="gate",
            field=models.IntegerField(default=2),
        ),
    ]
