# Generated by Django 5.2 on 2025-05-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air", "0018_alter_ticket_booking_reference_alter_ticket_gate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="booking_reference",
            field=models.CharField(
                default="W88PF70WEW", editable=False, max_length=10, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="gate",
            field=models.IntegerField(default=4),
        ),
    ]
