# Generated by Django 5.2 on 2025-07-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air", "0020_alter_ticket_booking_reference_alter_ticket_gate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="booking_reference",
            field=models.CharField(
                default="4IIV7PPOPV", editable=False, max_length=10, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="gate",
            field=models.IntegerField(default=5),
        ),
    ]
