# Generated by Django 5.2 on 2025-07-02 14:18

import air.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air", "0021_alter_ticket_booking_reference_alter_ticket_gate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airlineuser",
            options={
                "verbose_name": "Airline User",
                "verbose_name_plural": "Airline Users",
            },
        ),
        migrations.AlterModelOptions(
            name="airplane",
            options={"verbose_name": "Airplane", "verbose_name_plural": "Airplanes"},
        ),
        migrations.AlterModelOptions(
            name="baggage",
            options={"verbose_name": "Baggage", "verbose_name_plural": "Baggages"},
        ),
        migrations.AlterModelOptions(
            name="boardingpass",
            options={
                "verbose_name": "Boarding Pass",
                "verbose_name_plural": "Boarding Passes",
            },
        ),
        migrations.AlterModelOptions(
            name="checkin",
            options={"verbose_name": "Check-in", "verbose_name_plural": "Check-ins"},
        ),
        migrations.AlterModelOptions(
            name="comfort",
            options={"verbose_name": "Comfort", "verbose_name_plural": "Comforts"},
        ),
        migrations.AlterModelOptions(
            name="dietaryoption",
            options={
                "verbose_name": "Dietary Option",
                "verbose_name_plural": "Dietary Options",
            },
        ),
        migrations.AlterModelOptions(
            name="flight",
            options={"verbose_name": "Flight", "verbose_name_plural": "Flights"},
        ),
        migrations.AlterModelOptions(
            name="meal",
            options={"verbose_name": "Meal", "verbose_name_plural": "Meals"},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"verbose_name": "Ticket", "verbose_name_plural": "Tickets"},
        ),
        migrations.AlterField(
            model_name="airlineuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("passenger", "Passenger"),
                    ("gate_manager", "Gate Manager"),
                    ("checkin_manager", "Check-in Manager"),
                    ("supervisor", "Supervisor"),
                ],
                default="passenger",
                help_text="Defines the user role in the airline system",
                max_length=20,
                verbose_name="User Role",
            ),
        ),
        migrations.AlterField(
            model_name="airplane",
            name="name",
            field=models.CharField(
                help_text="Name of the airplane",
                max_length=100,
                verbose_name="Airplane name",
            ),
        ),
        migrations.AlterField(
            model_name="airplane",
            name="seat_capacity",
            field=models.PositiveIntegerField(
                help_text="Seat capacity of the airplane",
                verbose_name="Airplane seat capacity",
            ),
        ),
        migrations.AlterField(
            model_name="baggage",
            name="description",
            field=models.TextField(
                help_text="Description of the baggage",
                verbose_name="Baggage description",
            ),
        ),
        migrations.AlterField(
            model_name="baggage",
            name="name",
            field=models.CharField(
                help_text="Name of the baggage",
                max_length=100,
                verbose_name="Baggage name",
            ),
        ),
        migrations.AlterField(
            model_name="baggage",
            name="price",
            field=models.FloatField(
                help_text="Price of the baggage", verbose_name="Baggage price"
            ),
        ),
        migrations.AlterField(
            model_name="baggage",
            name="stripe_price_id",
            field=models.CharField(
                help_text="Stripe price id for payment",
                max_length=100,
                verbose_name="Stripe price ID",
            ),
        ),
        migrations.AlterField(
            model_name="baggage",
            name="weight",
            field=models.FloatField(
                help_text="Weight of the baggage", verbose_name="Baggage weight"
            ),
        ),
        migrations.AlterField(
            model_name="boardingpass",
            name="boarding_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Boarding time of the boarding pass",
                null=True,
                verbose_name="Boarding time",
            ),
        ),
        migrations.AlterField(
            model_name="boardingpass",
            name="gate_number",
            field=models.CharField(
                help_text="Gate number of the boarding pass",
                max_length=10,
                verbose_name="Gate number",
            ),
        ),
        migrations.AlterField(
            model_name="boardingpass",
            name="ticket",
            field=models.ForeignKey(
                help_text="Ticket of the boarding pass",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boarding_pass",
                to="air.ticket",
                verbose_name="Ticket",
            ),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="luggage_weight",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Luggage weight of the ticket",
                max_digits=5,
                verbose_name="Luggage weight",
            ),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="ticket",
            field=models.ForeignKey(
                help_text="Ticket of the checkin",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkins",
                to="air.ticket",
                verbose_name="Ticket",
            ),
        ),
        migrations.AlterField(
            model_name="comfort",
            name="description",
            field=models.TextField(
                help_text="Description of the comfort option",
                verbose_name="Comfort option description",
            ),
        ),
        migrations.AlterField(
            model_name="comfort",
            name="name",
            field=models.CharField(
                help_text="Name of the comfort option",
                max_length=100,
                verbose_name="Comfort option name",
            ),
        ),
        migrations.AlterField(
            model_name="comfort",
            name="price",
            field=models.FloatField(
                help_text="Price of the comfort option",
                verbose_name="Comfort option price",
            ),
        ),
        migrations.AlterField(
            model_name="comfort",
            name="stripe_price_id",
            field=models.CharField(
                help_text="Stripe price id for payment",
                max_length=100,
                verbose_name="Stripe price ID",
            ),
        ),
        migrations.AlterField(
            model_name="dietaryoption",
            name="name",
            field=models.CharField(
                max_length=50, verbose_name="Name of the food option"
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="airplane",
            field=models.ForeignKey(
                blank=True,
                help_text="Airplane of the flight",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flights",
                to="air.airplane",
                verbose_name="Airplane",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="arrival_time",
            field=models.DateTimeField(
                help_text="Arrival time of the flight", verbose_name="Arrival time"
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Base price (without services)",
                max_digits=8,
                verbose_name="Base price",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="departure_time",
            field=models.DateTimeField(
                help_text="Departure time of the flight", verbose_name="Departure time"
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="destination",
            field=models.CharField(
                help_text="Destination of the flight",
                max_length=100,
                verbose_name="Destination",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="destination_code",
            field=models.CharField(
                blank=True,
                help_text="Destination code of the flight",
                max_length=10,
                verbose_name="Destination code",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="flight_number",
            field=models.CharField(
                db_index=True,
                help_text="Unique flight number",
                max_length=10,
                unique=True,
                verbose_name="Flight number",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="origin",
            field=models.CharField(
                blank=True,
                help_text="Origin of the flight",
                max_length=100,
                null=True,
                verbose_name="Origin",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="origin_code",
            field=models.CharField(
                blank=True,
                help_text="Origin code of the flight",
                max_length=10,
                verbose_name="Origin code",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="status",
            field=models.CharField(
                choices=[
                    ("upcoming", "Upcoming"),
                    ("canceled", "Canceled"),
                    ("in_air", "In Air"),
                    ("arrived", "Arrived"),
                ],
                default="upcoming",
                help_text="Status of the flight",
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="description",
            field=models.TextField(
                help_text="Description of the meal", verbose_name="Meal description"
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="dietary_options",
            field=models.ManyToManyField(
                related_name="meals",
                to="air.dietaryoption",
                verbose_name="Dietary Options",
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="image_url",
            field=models.URLField(
                help_text="Image url of the meal", verbose_name="Meal image URL"
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="name",
            field=models.CharField(
                help_text="Name of the meal", max_length=100, verbose_name="Meal name"
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="price",
            field=models.FloatField(
                help_text="Price of the meal", verbose_name="Meal price"
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="stripe_price_id",
            field=models.CharField(
                help_text="Stripe price id for payment",
                max_length=100,
                verbose_name="Stripe price ID",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="baggage",
            field=models.ManyToManyField(
                blank=True,
                help_text="Baggage options of the ticket",
                related_name="tickets",
                to="air.baggage",
                verbose_name="Baggage options",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="booking_reference",
            field=models.CharField(
                db_index=True,
                default=air.models.generate_booking_reference,
                editable=False,
                help_text="Booking reference of the ticket",
                max_length=10,
                unique=True,
                verbose_name="Booking reference",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="comforts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Comfort options of the ticket",
                related_name="tickets",
                to="air.comfort",
                verbose_name="Comfort options",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Ticket creating time",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="flight",
            field=models.ForeignKey(
                help_text="Flight of the ticket",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="air.flight",
                verbose_name="Flight",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="gate",
            field=models.IntegerField(
                default=2, help_text="Gate of the ticket", verbose_name="Gate"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="is_boarded",
            field=models.BooleanField(
                default=False,
                help_text="Is passenger boarded",
                verbose_name="Is passenger boarded",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="is_checked_in",
            field=models.BooleanField(
                default=False,
                help_text="Is passenger checked in",
                verbose_name="Is passenger checked in",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="meals",
            field=models.ManyToManyField(
                blank=True,
                help_text="Meals of the ticket",
                related_name="tickets",
                to="air.meal",
                verbose_name="Meals",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="passenger",
            field=models.ForeignKey(
                help_text="Passenger of the ticket",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Passenger",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price of the ticket",
                max_digits=8,
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seat_class",
            field=models.CharField(
                choices=[
                    ("economy", "Economy"),
                    ("business", "Business"),
                    ("first", "First"),
                ],
                default="economy",
                help_text="Seat class of the ticket",
                max_length=20,
                verbose_name="Seat class",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seat_number",
            field=models.CharField(
                help_text="Seat number of the ticket",
                max_length=5,
                verbose_name="Seat number",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("upcoming", "Upcoming"),
                    ("canceled", "Canceled"),
                    ("boarded", "Boarded"),
                    ("checked_in", "Checked In"),
                    ("late", "Late"),
                    ("used", "Used"),
                ],
                default="upcoming",
                help_text="Status of the ticket",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
