# Generated by Django 5.2 on 2025-07-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air", "0001_initial_squashed_0023_alter_ticket_gate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="gate",
            field=models.IntegerField(
                default=2, help_text="Gate of the ticket", verbose_name="Gate"
            ),
        ),
    ]
