# Generated by Django 5.2 on 2025-07-08 15:58

import air.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air", "0025_alter_ticket_gate"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="business_seats",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Seat capacity of the airplane",
                verbose_name="Airplane business seats",
            ),
        ),
        migrations.AddField(
            model_name="airplane",
            name="economy_seats",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Seat capacity of the airplane",
                verbose_name="Airplane economy seats",
            ),
        ),
        migrations.AddField(
            model_name="airplane",
            name="first_class_seats",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Seat capacity of the airplane",
                verbose_name="Airplane first class seats",
            ),
        ),
        migrations.AlterField(
            model_name="baggage",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price of the baggage",
                max_digits=8,
                verbose_name="Baggage price",
            ),
        ),
        migrations.AlterField(
            model_name="comfort",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price of the comfort option",
                max_digits=8,
                verbose_name="Comfort option price",
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price of the meal",
                max_digits=8,
                verbose_name="Meal price",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="gate",
            field=models.IntegerField(
                default=air.utils.get_random_gate,
                help_text="Gate of the ticket",
                verbose_name="Gate",
            ),
        ),
        migrations.CreateModel(
            name="Seats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seat_number",
                    models.CharField(
                        choices=[
                            ("economy", "Economy"),
                            ("business", "Business"),
                            ("first", "First"),
                        ],
                        default="economy",
                        max_length=10,
                    ),
                ),
                (
                    "stripe_price_id",
                    models.CharField(
                        choices=[
                            ("price_1RP0yYQMzydK9SUprJfIiJYw", "Economy price"),
                            ("price_1RP0yyQMzydK9SUpQVDc8Xlz", "Business price"),
                            ("price_1RP0zFQMzydK9SUptZsV3qKC", "First class price"),
                        ],
                        default="price_1RP0yYQMzydK9SUprJfIiJYw",
                        max_length=100,
                        verbose_name="Stripe price ID",
                    ),
                ),
                (
                    "is_reserved",
                    models.BooleanField(default=False, verbose_name="Is reserved"),
                ),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="air.flight",
                        verbose_name="seats",
                    ),
                ),
            ],
        ),
    ]
