# Generated by Django 5.2 on 2025-07-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air", "0026_airplane_business_seats_airplane_economy_seats_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seats",
            name="seat_class",
            field=models.CharField(
                choices=[
                    ("economy", "Economy"),
                    ("business", "Business"),
                    ("first", "First"),
                ],
                default="economy",
                help_text="Seat class of the ticket",
                max_length=20,
                verbose_name="Seat class",
            ),
        ),
    ]
