# Generated by Django 5.2 on 2025-07-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air", "0027_seats_seat_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seats",
            name="seat_class",
            field=models.CharField(
                choices=[
                    ("economy", "Economy"),
                    ("business", "Business"),
                    ("first", "First"),
                ],
                default="economy",
                help_text="Seat class of the seat",
                max_length=20,
                verbose_name="Seat class",
            ),
        ),
        migrations.AlterField(
            model_name="seats",
            name="seat_number",
            field=models.CharField(
                choices=[
                    ("economy", "Economy"),
                    ("business", "Business"),
                    ("first", "First"),
                ],
                max_length=10,
            ),
        ),
    ]
