# Generated by Django 5.2 on 2025-07-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air", "0028_alter_seats_seat_class_alter_seats_seat_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seats",
            name="seat_number",
            field=models.CharField(max_length=10),
        ),
    ]
